server:
  port: 9090
  
spring:
  cloud:
    gateway:
      routes:
      - id: livro_service_route
        uri: http://localhost:8080
        predicates:
        - Path=/livros
      - id: avalicacao_service_route
        uri: http://localhost:8081
        predicates:
        - Path=/avaliacoes
    config:
      name: gateway
    consul:
      host: localhost
      port: 8500
      discovery:
        instanceId: ${spring.cloud.config.name}:${random.value}
        serviceName: ${spring.cloud.config.name}

management:
  endpoints:
    web:
      exposure:
        include: "*"
